name: ECS Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "the environment to deploy to (terraform isnt valid)"
        type: environment
      image_tag:
        description: "Image tag to deploy"
        required: true
      task_definition_revision_api:
        description: "Optional: Task Definition Revision, to base deployment off of"
        required: false
        default: "latest"
      task_definition_revision_consumer:
        description: "Optional: Task Definition Revision, to base deployment off of"
        required: false
        default: "latest"

jobs:
  deploy_consumer:
    uses: QuickPay/github-actions-callable-workflows/.github/workflows/call-ecs-deploy.yml@master
    with:
      image_name: ${{ github.event.repository.name }
      image_tag: ${{ github.event.inputs.image_tag }}
      scope: "pci"
      environment: ${{ github.event.inputs.environment }}
      application_name: ${{ github.event.repository.name }-consumer
      cluster_name: "backend"
      task_definition_revision: ${{ github.event.inputs.task_definition_revision_consumer }}
    secrets: inherit

  deploy_api:
    uses: QuickPay/github-actions-callable-workflows/.github/workflows/call-ecs-deploy.yml@master
    with:
      image_name: ${{ github.event.repository.name }
      image_tag: ${{ github.event.inputs.image_tag }}
      scope: "pci"
      environment: ${{ github.event.inputs.environment }}
      application_name: ${{ github.event.repository.name }-api
      cluster_name: "backend"
      task_definition_revision: ${{ github.event.inputs.task_definition_revision_api }}
    secrets: inherit

  slack_message:
    needs: [ deploy_api, deploy_consumer ]
    uses: QuickPay/github-actions-callable-workflows/.github/workflows/call-slack-deploy-messsage.yml@master
    with:
      tag: ${{ inputs.image_tag }}
      scope: "pci"
      user: ${{ github.actor }}
      environment: ${{ inputs.environment }}
    secrets: inherit
