name: Terraform Apply

on:
  issue_comment:
    types: [created]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - run: echo "true"
  check_apply:
    runs-on: ubuntu-latest
    if: github.event.comment.body == '@apply stag' || github.event.comment.body == '@apply prod'
    steps:
      - run: echo "true"
  apply:
    runs-on: ubuntu-latest
    needs: [check_pr, check_apply]
    strategy:
      fail-fast: false
      matrix:
        name:
          - internal-stag
          - internal-prod
          - nonpci-stag
          - nonpci-prod
          - pci-stag
          - pci-prod
    environment: terraform
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.QUICKPAY_TOOLS_READONLY_SSH_KEY_PRIVATE }}

      - name: Extract PR number
        id: pr
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "number=$PR_NUM" >> $GITHUB_OUTPUT

      - name: Fail if Unapproved
        uses: actions/github-script@v6
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        with:
          script: |
            const { COMMENT_BODY } = process.env

            const pr_num = parseInt("${{ steps.pr.outputs.number }}")
            const query = `
            query($owner:String!, $name:String!, $pr_num:Int!) {
              repository(name: $name, owner: $owner) {
                pullRequest(number: $pr_num) {
                  reviewDecision
                }
              }
            }
            `
            const result = await github.graphql(query, {
              pr_num,
              owner: context.repo.owner,
              name: context.repo.repo,
            })
            const review = result.repository.pullRequest.reviewDecision
            if (review !== "APPROVED" && COMMENT_BODY === "@apply prod") {
              core.setFailed('Pull request must be approved to apply to prod')
            }

      - name: Extract is_run
        id: is_run
        run: |
          if [[ "${{ github.event.comment.body }}" = *"stag" ]]; then
            if [[ "${{ matrix.name }}" = *"stag" ]]; then
              echo "is_run=stag" >> $GITHUB_OUTPUT
              echo "ENV=stag" >> $GITHUB_ENV
            fi
          elif [[ "${{ github.event.comment.body }}" = *"prod" ]]; then
            echo "is_run=prod" >> $GITHUB_OUTPUT
            echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Extract credentials
        if: steps.is_run.outputs.is_run
        id: credentials
        env:
          NAME: ${{ matrix.name }}
        run: |
          declare -A access_key_ids=(
            ["internal-stag"]="${{ secrets.STAG_INTERNAL_AWS_ACCESS_KEY_ID }}"
            ["internal-prod"]="${{ secrets.PROD_INTERNAL_AWS_ACCESS_KEY_ID }}"
            ["nonpci-stag"]="${{ secrets.STAG_NONPCI_AWS_ACCESS_KEY_ID }}"
            ["nonpci-prod"]="${{ secrets.PROD_NONPCI_AWS_ACCESS_KEY_ID }}"
            ["pci-stag"]="${{ secrets.STAG_PCI_AWS_ACCESS_KEY_ID }}"
            ["pci-prod"]="${{ secrets.PROD_PCI_AWS_ACCESS_KEY_ID }}"
          )
          declare -A secret_access_keys=(
            ["internal-stag"]="${{ secrets.STAG_INTERNAL_AWS_SECRET_ACCESS_KEY }}"
            ["internal-prod"]="${{ secrets.PROD_INTERNAL_AWS_SECRET_ACCESS_KEY }}"
            ["nonpci-stag"]="${{ secrets.STAG_NONPCI_AWS_SECRET_ACCESS_KEY }}"
            ["nonpci-prod"]="${{ secrets.PROD_NONPCI_AWS_SECRET_ACCESS_KEY }}"
            ["pci-stag"]="${{ secrets.STAG_PCI_AWS_SECRET_ACCESS_KEY }}"
            ["pci-prod"]="${{ secrets.PROD_PCI_AWS_SECRET_ACCESS_KEY }}"
          )
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "access_key_id=${access_key_ids[$NAME]}" >> $GITHUB_OUTPUT
          echo "secret_access_key=${secret_access_keys[$NAME]}" >> $GITHUB_OUTPUT
          echo "GRAFANA_AUTH=${{ secrets.GRAFANA_API_KEY }}" >> $GITHUB_ENV
          echo "HUMIO_API_TOKEN=${{ secrets.HUMIO_API_TOKEN }}" >> $GITHUB_ENV
          declare -A slack_webhook_deploy=(
            ["stag"]="${{ secrets.SLACK_WEBHOOK_TECH_QP_DEPLOYS_STAGING }}"
            ["prod"]="${{ secrets.SLACK_WEBHOOK_TECH_QP_DEPLOYS }}"
          )
          echo "slack_webhook_deploy=${slack_webhook_deploy[$ENV]}" >> $GITHUB_OUTPUT

      - uses: aws-actions/configure-aws-credentials@v2
        if: steps.is_run.outputs.is_run
        with:
          aws-access-key-id: ${{ steps.credentials.outputs.access_key_id }}
          aws-secret-access-key: ${{ steps.credentials.outputs.secret_access_key }}
          aws-region: eu-central-1

      - name: resolve pr refs
        if: steps.is_run.outputs.is_run
        id: refs
        uses: eficode/resolve-pr-refs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        if: steps.is_run.outputs.is_run
        with:
          fetch-depth: 0
          ref: ${{ steps.refs.outputs.head_ref }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Find plan
        if: steps.is_run.outputs.is_run
        id: find_plan
        env:
          PLAN_BRANCH: __plan_branch_${{ steps.credentials.outputs.name }}
        run: |
          export PR_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          export COMMIT_SHA=$(git log -n 1 --pretty=format:"%H")  
          echo $PR_BRANCH
          echo "pr_branch=$PR_BRANCH" >> $GITHUB_OUTPUT
          echo $COMMIT_SHA
          git checkout $PLAN_BRANCH
          git pull origin $PLAN_BRANCH
          mv ./$COMMIT_SHA.tfplan /tmp/plan.tfplan
          git checkout $PR_BRANCH
          mv /tmp/plan.tfplan ./terraform/plan.tfplan

      - name: Apply plan
        if: steps.is_run.outputs.is_run
        run: |
          cd terraform

          if [[ -d main ]]; then
            mv plan.tfplan main/plan.tfplan
            cd main
          fi

          terraform init -input=false
          terraform workspace select quickpay-${{ matrix.name }}
          terraform apply -input=false plan.tfplan -no-color 2>&1 | tee -a /tmp/apply.txt

      - name: Upload Apply to Pastie
        if: steps.is_run.outputs.is_run
        id: pastie
        uses: QuickPay/pastie-upload-action@v1.1.0
        with:
          credentials: ${{ secrets.PASTIE_CREDENTIALS }}
          document_path: "/tmp/apply.txt"

      - name: "Comment PR"
        if: steps.is_run.outputs.is_run
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_num = parseInt("${{ steps.pr.outputs.number }}")
            const { repo: { owner, repo }  } = context;
            const url = "${{ steps.pastie.outputs.url }}";
            const title = "# ${{ steps.credentials.outputs.name }} Apply";
            const body = `${title}\n${url}`;
            github.rest.issues.createComment({ issue_number: pr_num, owner, repo, body: body });

      - name: Slack Notification
        if: steps.is_run.outputs.is_run
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ steps.credentials.outputs.slack_webhook_deploy }}
          SLACK_MESSAGE: "*${{ matrix.name }}:* ${{ github.actor }} applied terraform for *${{ github.event.repository.name }}:${{ steps.find_plan.outputs.pr_branch }}*. See result at: ${{ steps.pastie.outputs.url }}"
          MSG_MINIMAL: true
          SLACK_FOOTER: ""
          SLACK_MSG_AUTHOR: " "
          SLACK_TITLE: " "
