name: Terraform Module Lint and fmt

on:
  push:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - uses: actions/checkout@v3

      - run: |
          terraform fmt -check -diff

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.45.0

      - uses: actions/checkout@v3

      - run: |
          tflint --init
          tflint --config ./.tflint.hcl
