name: Terraform Lint and fmt

on:
  push:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.1

      - uses: actions/checkout@v2

      - run: |
          terraform fmt -check -diff

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.1

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.41.0

      - uses: actions/checkout@v2

      - run: |
          tflint --init
          tflint --config ./.tflint.hcl
